# Generated by Django 5.1.6 on 2025-02-21 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='receiver',
        ),
        migrations.AddField(
            model_name='invitation',
            name='receiver',
            field=models.ManyToManyField(related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
